services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: fms
      POSTGRES_PASSWORD: fms
      POSTGRES_DB: fms_booking
    ports:
      - "5432:5432"
    volumes:
      - fms_pg_data:/var/lib/postgresql/data

volumes:
  fms_pg_data:
