/** Auto-generated by scripts/build-george-li-gallery.ts — do not edit by hand. */
export const GEORGE_LI_GALLERY_SLIDES = [
  {
    "src": "/images/about-d-festival/george-li-gallery/slide-01.webp",
    "width": 1024,
    "height": 682
  },
  {
    "src": "/images/about-d-festival/george-li-gallery/slide-02.webp",
    "width": 1024,
    "height": 618
  },
  {
    "src": "/images/about-d-festival/george-li-gallery/slide-03.webp",
    "width": 1024,
    "height": 661
  },
  {
    "src": "/images/about-d-festival/george-li-gallery/slide-04.webp",
    "width": 1024,
    "height": 675
  },
  {
    "src": "/images/about-d-festival/george-li-gallery/slide-05.webp",
    "width": 1024,
    "height": 608
  },
  {
    "src": "/images/about-d-festival/george-li-gallery/slide-06.webp",
    "width": 994,
    "height": 796
  },
  {
    "src": "/images/about-d-festival/george-li-gallery/slide-07.webp",
    "width": 1024,
    "height": 641
  },
  {
    "src": "/images/about-d-festival/george-li-gallery/slide-08.webp",
    "width": 1024,
    "height": 602
  },
  {
    "src": "/images/about-d-festival/george-li-gallery/slide-09.webp",
    "width": 1024,
    "height": 698
  },
  {
    "src": "/images/about-d-festival/george-li-gallery/slide-10.webp",
    "width": 1024,
    "height": 640
  },
  {
    "src": "/images/about-d-festival/george-li-gallery/slide-11.webp",
    "width": 1024,
    "height": 646
  },
  {
    "src": "/images/about-d-festival/george-li-gallery/slide-12.webp",
    "width": 1024,
    "height": 644
  },
  {
    "src": "/images/about-d-festival/george-li-gallery/slide-13.webp",
    "width": 1024,
    "height": 618
  },
  {
    "src": "/images/about-d-festival/george-li-gallery/slide-14.webp",
    "width": 1024,
    "height": 764
  },
  {
    "src": "/images/about-d-festival/george-li-gallery/slide-15.webp",
    "width": 890,
    "height": 690
  },
  {
    "src": "/images/about-d-festival/george-li-gallery/slide-16.webp",
    "width": 1024,
    "height": 614
  },
  {
    "src": "/images/about-d-festival/george-li-gallery/slide-17.webp",
    "width": 1024,
    "height": 610
  }
] as const;
