/**
 * Builds optimized WebP slides for the George Li portrait gallery on the about page.
 * Expects:
 *   - public/images/about-d-festival/george-li-portrait.png (slide 1)
 *   - public/images/about-d-festival/george-li-gallery-source/upload-01.png, upload-02.png, … (any count)
 *
 * Run: npx tsx scripts/build-george-li-gallery.ts
 */
import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import sharp from "sharp";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const OUT_DIR = path.join(ROOT, "public/images/about-d-festival/george-li-gallery");
const MANIFEST_OUT = path.join(ROOT, "src/lib/about-d-festival/george-li-gallery-slides.ts");
const PORTRAIT = path.join(ROOT, "public/images/about-d-festival/george-li-portrait.png");
const SOURCE_DIR = path.join(ROOT, "public/images/about-d-festival/george-li-gallery-source");

const MAX_EDGE = 1600;
const WEBP_QUALITY = 82;

async function toWebpSlide(input: string, output: string) {
  const pipeline = sharp(input).rotate().resize({
    width: MAX_EDGE,
    height: MAX_EDGE,
    fit: "inside",
    withoutEnlargement: true,
  });
  await pipeline.webp({ quality: WEBP_QUALITY, effort: 4, smartSubsample: true }).toFile(output);
  const meta = await sharp(output).metadata();
  if (!meta.width || !meta.height) throw new Error(`Missing dimensions: ${output}`);
  return { width: meta.width, height: meta.height };
}

async function main() {
  await fs.mkdir(OUT_DIR, { recursive: true });

  const uploads = (await fs.readdir(SOURCE_DIR))
    .filter((n) => /^upload-\d+\.png$/i.test(n))
    .sort((a, b) => {
      const na = parseInt(a.match(/\d+/)![0], 10);
      const nb = parseInt(b.match(/\d+/)![0], 10);
      return na - nb;
    });

  if (uploads.length === 0) {
    throw new Error(`No upload-NN.png files in ${SOURCE_DIR}`);
  }

  const inputs = [PORTRAIT, ...uploads.map((u) => path.join(SOURCE_DIR, u))];

  const slides: { src: string; width: number; height: number }[] = [];
  let i = 1;
  for (const input of inputs) {
    await fs.access(input);
    const base = `slide-${String(i).padStart(2, "0")}.webp`;
    const out = path.join(OUT_DIR, base);
    const { width, height } = await toWebpSlide(input, out);
    slides.push({ src: `/images/about-d-festival/george-li-gallery/${base}`, width, height });
    i += 1;
  }

  const ts = `/** Auto-generated by scripts/build-george-li-gallery.ts — do not edit by hand. */\nexport const GEORGE_LI_GALLERY_SLIDES = ${JSON.stringify(slides, null, 2)} as const;\n`;
  await fs.mkdir(path.dirname(MANIFEST_OUT), { recursive: true });
  await fs.writeFile(MANIFEST_OUT, ts, "utf8");

  for (const name of await fs.readdir(OUT_DIR)) {
    const m = /^slide-(\d+)\.webp$/i.exec(name);
    if (!m) continue;
    if (parseInt(m[1], 10) > slides.length) {
      await fs.unlink(path.join(OUT_DIR, name));
    }
  }

  const totalBytes = (
    await Promise.all(slides.map((s) => fs.stat(path.join(ROOT, "public", s.src.slice(1)))))
  ).reduce((a, st) => a + st.size, 0);

  console.log(`Wrote ${slides.length} slides to ${path.relative(ROOT, OUT_DIR)}`);
  console.log(`Total WebP size: ${(totalBytes / 1024 / 1024).toFixed(2)} MiB`);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
